# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SwiftStudies' do
    
use_frameworks!

pod 'Alamofire', '~> 1.2'
pod 'AlamofireObjectMapper', '~> 0.2'

end

target 'SwiftStudiesTests' do

end

